[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner     = "probe-rs run --chip RP2040"

rustflags  = [
  "-C",   "linker=flip-link",
  "-C",   "link-arg=--nmagic",
  "-C",   "link-arg=-Tlink.x",
  "-Z",   "trap-unreachable=no",
  "-C",   "no-vectorize-loops",
  # "-Z", "mir-opt-level=4",
]

[build]
target    = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
